import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { X, Upload, Loader2, Plus } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";
import { apiUrls } from "@/config/api";
import { toast } from "sonner";

interface News {
  id: number;
  title: string;
  slug: string;
  summary: string;
  content: string;
  image?: string;
  images?: string[];
  author: string;
  status: string;
  featured: boolean;
  published_at?: string;
  created_at: string;
  updated_at: string;
}

interface NewsEditorProps {
  news?: News | null;
  isOpen: boolean;
  onClose: () => void;
  onSave: (newsData: News) => void;
}

const NewsEditor = ({ news, isOpen, onClose, onSave }: NewsEditorProps) => {
  const { token } = useAuth();
  const [title, setTitle] = useState(news?.title || "");
  const [summary, setSummary] = useState(news?.summary || "");
  const [content, setContent] = useState(news?.content || "");
  const [image, setImage] = useState(news?.image || "");
  const [images, setImages] = useState<string[]>(news?.images || []);
  const [author, setAuthor] = useState(news?.author || "");
  const [status, setStatus] = useState(news?.status || "draft");
  const [featured, setFeatured] = useState(news?.featured || false);
  const [imageFile, setImageFile] = useState<File | null>(null);
  const [uploading, setUploading] = useState(false);

  useEffect(() => {
    // Reset all fields when news changes
    if (news) {
      setTitle(news.title || "");
      setSummary(news.summary || "");
      setContent(news.content || "");
      setImage(news.image || "");
      setImages(news.images || []);
      setAuthor(news.author || "");
      setStatus(news.status || "draft");
      setFeatured(news.featured || false);
      setImageFile(null);
      setUploading(false);
    } else {
      // Reset to defaults when creating new news
      setTitle("");
      setSummary("");
      setContent("");
      setImage("");
      setImages([]);
      setAuthor("");
      setStatus("draft");
      setFeatured(false);
      setImageFile(null);
      setUploading(false);
    }
  }, [news]);

  const handleImageUpload = async (file: File, isAdditional: boolean = false) => {
    if (!token) {
      toast.error('You must be logged in to upload images');
      return;
    }

    setUploading(true);
    try {
      const formData = new FormData();
      formData.append('image', file);
      formData.append('folder', 'news');

      const response = await fetch(apiUrls.uploadImage(), {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`,
        },
        body: formData,
      });

      if (response.ok) {
        const result = await response.json();
        if (result.success && result.data.url) {
          if (isAdditional) {
            // Add to additional images array
            setImages([...images, result.data.url]);
            toast.success('Additional image added');
          } else {
            // Set as main image
            setImage(result.data.url);
            toast.success('Main image uploaded');
          }
          setImageFile(null);
        }
      } else {
        const errorData = await response.json();
        toast.error(errorData.message || 'Failed to upload image');
      }
    } catch (error) {
      console.error('Error uploading image:', error);
      toast.error('An error occurred while uploading the image');
    } finally {
      setUploading(false);
    }
  };

  const removeAdditionalImage = (index: number) => {
    const newImages = images.filter((_, i) => i !== index);
    setImages(newImages);
    toast.success('Image removed');
  };

  const handleSave = () => {
    // Don't send blob URLs to the backend - they won't work
    let finalImage = image;
    if (image && image.startsWith('blob:')) {
      // If user selected a file but didn't provide a URL, clear the image
      // In a production environment, you would upload the file to a server first
      console.warn('Blob URL detected - clearing image. Please enter an image URL or upload to server first.');
      finalImage = '';
    }

    const newsData: News = {
      id: news?.id || Date.now(),
      title,
      slug: "", // Will be generated by backend
      summary,
      content,
      image: finalImage,
      images: images.length > 0 ? images : undefined,
      author,
      status,
      featured,
      published_at: status === 'published' ? new Date().toISOString() : undefined,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString()
    };
    onSave(newsData);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <Card className="w-full max-w-4xl max-h-[90vh] overflow-y-auto">
        <CardHeader className="flex flex-row items-center justify-between">
          <CardTitle>{news ? "Edit News Article" : "Create New News Article"}</CardTitle>
          <Button variant="ghost" size="sm" onClick={onClose}>
            <X className="h-4 w-4" />
          </Button>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="space-y-2">
            <Label htmlFor="title">News Title *</Label>
            <Input
              id="title"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="Enter news title"
              required
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="author">Author</Label>
            <Input
              id="author"
              value={author}
              onChange={(e) => setAuthor(e.target.value)}
              placeholder="Enter author name"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="status">Status</Label>
            <Select value={status} onValueChange={setStatus}>
              <SelectTrigger>
                <SelectValue placeholder="Select status" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="draft">Draft</SelectItem>
                <SelectItem value="published">Published</SelectItem>
                <SelectItem value="archived">Archived</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2">
            <Label htmlFor="summary">Summary</Label>
            <Textarea
              id="summary"
              value={summary}
              onChange={(e) => setSummary(e.target.value)}
              placeholder="Enter a brief summary of the news article"
              className="min-h-[80px]"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="content">Content *</Label>
            <Textarea
              id="content"
              value={content}
              onChange={(e) => setContent(e.target.value)}
              placeholder="Enter the full news article content"
              className="min-h-[200px]"
              required
            />
          </div>

          {/* Main Image */}
          <div className="space-y-2">
            <Label htmlFor="image">Main News Image</Label>
            
            {/* Image Preview */}
            {image && !image.startsWith('blob:') && (
              <div className="mb-3 p-3 border rounded-lg bg-gray-50">
                <img 
                  src={image} 
                  alt="News preview" 
                  className="w-full max-w-md h-64 object-cover rounded border mx-auto"
                  onError={(e) => {
                    (e.target as HTMLImageElement).src = '/placeholder.svg';
                  }}
                />
                <div className="flex items-center justify-between mt-2">
                  <p className="text-xs text-gray-600">Main image</p>
                  <Button 
                    type="button"
                    variant="ghost" 
                    size="sm"
                    onClick={() => setImage('')}
                    className="text-red-600 hover:text-red-700"
                    disabled={uploading}
                  >
                    <X className="h-4 w-4 mr-1" />
                    Remove
                  </Button>
                </div>
              </div>
            )}

            {/* File Upload */}
            <div className="border-2 border-dashed border-gray-300 rounded-lg p-6 text-center hover:border-church-red transition-colors bg-gray-50">
              <Input
                id="image-file"
                type="file"
                accept="image/*"
                onChange={(e) => {
                  const file = e.target.files?.[0];
                  if (file) {
                    handleImageUpload(file, false);
                  }
                }}
                className="hidden"
                disabled={uploading}
              />
              <label htmlFor="image-file" className="cursor-pointer block">
                {uploading ? (
                  <div className="flex flex-col items-center justify-center py-2">
                    <Loader2 className="h-8 w-8 animate-spin text-church-red mb-2" />
                    <p className="text-sm font-medium">Uploading...</p>
                  </div>
                ) : (
                  <div className="py-2">
                    <Upload className="h-8 w-8 mx-auto text-gray-400 mb-2" />
                    <p className="text-sm font-medium text-gray-700">Upload main image</p>
                    <p className="text-xs text-gray-400 mt-1">PNG, JPG, GIF, WEBP up to 60MB</p>
                  </div>
                )}
              </label>
            </div>
          </div>

          {/* Additional Images Gallery */}
          <div className="space-y-2">
            <Label>Additional Images (Gallery)</Label>
            <p className="text-xs text-muted-foreground">Upload additional images for this news article</p>
            
            {/* Display current additional images */}
            {images.length > 0 && (
              <div className="grid grid-cols-3 gap-3 mb-3">
                {images.map((imgUrl, index) => (
                  <div key={index} className="relative group">
                    <img 
                      src={imgUrl} 
                      alt={`Additional ${index + 1}`} 
                      className="w-full h-32 object-cover rounded border"
                      onError={(e) => {
                        (e.target as HTMLImageElement).src = '/placeholder.svg';
                      }}
                    />
                    <Button 
                      type="button"
                      variant="destructive"
                      size="icon"
                      className="absolute top-1 right-1 h-6 w-6 opacity-0 group-hover:opacity-100 transition-opacity"
                      onClick={() => removeAdditionalImage(index)}
                    >
                      <X className="h-3 w-3" />
                    </Button>
                  </div>
                ))}
              </div>
            )}

            {/* Upload Additional Image */}
            <div className="border-2 border-dashed border-gray-200 rounded-lg p-4 text-center hover:border-church-red/50 transition-colors">
              <Input
                id="additional-image-file"
                type="file"
                accept="image/*"
                onChange={(e) => {
                  const file = e.target.files?.[0];
                  if (file) {
                    handleImageUpload(file, true);
                    e.target.value = ''; // Reset input to allow same file again
                  }
                }}
                className="hidden"
                disabled={uploading}
              />
              <label htmlFor="additional-image-file" className="cursor-pointer block">
                <div className="py-2">
                  <Plus className="h-6 w-6 mx-auto text-gray-400 mb-1" />
                  <p className="text-xs font-medium text-gray-600">Add more images</p>
                </div>
              </label>
            </div>
          </div>

          <div className="flex items-center space-x-2">
            <input
              type="checkbox"
              id="featured"
              checked={featured}
              onChange={(e) => setFeatured(e.target.checked)}
              className="rounded"
            />
            <Label htmlFor="featured">Featured News</Label>
          </div>

          <div className="flex justify-end space-x-4">
            <Button variant="outline" onClick={onClose}>
              Cancel
            </Button>
            <Button onClick={handleSave}>
              {news ? "Update News Article" : "Create News Article"}
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default NewsEditor;




